#!/bin/bash

if [[ -n "$1" ]]; then
	urlval=$(echo "Search in archwiki:" | dmenu | awk '{print "https://wiki.archlinux.org/index.php?search=" $1}')
	test -f $urlval || $1 $urlval 
else
	msg="archwiki: need a browser as argument" 
	echo $msg ; notify-send -u critical "$msg"
fi
